// //----------------------
// // <auto-generated>
// //     Generated using the NSwag toolchain v5.6.6095.40772 (NJsonSchema v4.8.6094.34027) (http://NSwag.org)
// // </auto-generated>
// //----------------------
//
// import 'rxjs/Rx';
// import {Observable} from 'rxjs/Observable';
// import {Injectable, Inject, Optional, OpaqueToken} from '@angular/core';
// import {Http, Headers, Response, RequestOptionsArgs} from '@angular/http';
//
// module api.module.ts {
// export const API_BASE_URL = new OpaqueToken('API_BASE_URL');
// export const JSON_PARSE_REVIVER = new OpaqueToken('JSON_PARSE_REVIVER');
//
// export interface IClient {
//     api(): Observable<void>;
//     swaggerSchemaRaw(): Observable<void>;
//     swaggerSchema(): Observable<void>;
// }
//
// @Injectable()
// export class Client implements IClient {
//     private http: Http = null;
//     private baseUrl: string = undefined;
//     private jsonParseReviver: (key: string, value: any) => any = undefined;
//
//     constructor(@Inject(Http) http: Http, @Optional() @Inject(API_BASE_URL) baseUrl?: string, @Optional() @Inject(JSON_PARSE_REVIVER) jsonParseReviver?: (key: string, value: any) => any) {
//         this.http = http;
//         this.baseUrl = baseUrl ? baseUrl : "http://http://localhost:8000/swagger-schema";
//         this.jsonParseReviver = jsonParseReviver;
//     }
//
//     api(): Observable<void> {
//         var url = this.baseUrl + "/api";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processApi(response);
//         });
//     }
//
//     private processApi(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     swaggerSchemaRaw(): Observable<void> {
//         var url = this.baseUrl + "/swagger-schema-raw";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processSwaggerSchemaRaw(response);
//         });
//     }
//
//     private processSwaggerSchemaRaw(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     swaggerSchema(): Observable<void> {
//         var url = this.baseUrl + "/swagger-schema";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processSwaggerSchema(response);
//         });
//     }
//
//     private processSwaggerSchema(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
// }
//
// export interface IApiClient {
//     dudes(pk: string, name: string, still_here: string): Observable<void>;
//     dudes(pk: string): Observable<void>;
//     dudes(pk: string, name: string, still_here: string): Observable<void>;
//     dudes(pk: string): Observable<void>;
//     bills(description: string, date: string, amount: string, owner: string, affected_dudes: string): Observable<void>;
//     bills(page: string): Observable<void>;
//     bills(pk: string, description: string, date: string, amount: string, owner: string, affected_dudes: string): Observable<void>;
//     bills(pk: string): Observable<void>;
//     bills(pk: string, description: string, date: string, amount: string, owner: string, affected_dudes: string): Observable<void>;
//     bills(pk: string): Observable<void>;
//     dudes(name: string, still_here: string): Observable<void>;
//     dudes(page: string): Observable<void>;
//     payments(pk: string, bill: string, by: string, at: string, amount: string): Observable<void>;
//     payments(pk: string): Observable<void>;
//     payments(pk: string, bill: string, by: string, at: string, amount: string): Observable<void>;
//     payments(pk: string): Observable<void>;
//     payments(bill: string, by: string, at: string, amount: string): Observable<void>;
//     payments(page: string): Observable<void>;
// }
//
// @Injectable()
// export class ApiClient implements IApiClient {
//     private http: Http = null;
//     private baseUrl: string = undefined;
//     private jsonParseReviver: (key: string, value: any) => any = undefined;
//
//     constructor(@Inject(Http) http: Http, @Optional() @Inject(API_BASE_URL) baseUrl?: string, @Optional() @Inject(JSON_PARSE_REVIVER) jsonParseReviver?: (key: string, value: any) => any) {
//         this.http = http;
//         this.baseUrl = baseUrl ? baseUrl : "http://http://localhost:8000/swagger-schema";
//         this.jsonParseReviver = jsonParseReviver;
//     }
//
//     dudes(pk: string, name: string, still_here: string): Observable<void> {
//         var url = this.baseUrl + "/api/dudes/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "put",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processDudes(response);
//         });
//     }
//
//     private processDudes(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     dudes(pk: string): Observable<void> {
//         var url = this.baseUrl + "/api/dudes/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "delete",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processDudes(response);
//         });
//     }
//
//     private processDudes(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "204") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     dudes(pk: string, name: string, still_here: string): Observable<void> {
//         var url = this.baseUrl + "/api/dudes/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "patch",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processDudes(response);
//         });
//     }
//
//     private processDudes(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     dudes(pk: string): Observable<void> {
//         var url = this.baseUrl + "/api/dudes/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processDudes(response);
//         });
//     }
//
//     private processDudes(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     bills(description: string, date: string, amount: string, owner: string, affected_dudes: string): Observable<void> {
//         var url = this.baseUrl + "/api/bills";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "post",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processBills(response);
//         });
//     }
//
//     private processBills(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "201") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     bills(page: string): Observable<void> {
//         var url = this.baseUrl + "/api/bills?";
//
//         if (page !== undefined)
//             url += "page=" + encodeURIComponent("" + page) + "&";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processBills(response);
//         });
//     }
//
//     private processBills(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     bills(pk: string, description: string, date: string, amount: string, owner: string, affected_dudes: string): Observable<void> {
//         var url = this.baseUrl + "/api/bills/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "put",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processBills(response);
//         });
//     }
//
//     private processBills(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     bills(pk: string): Observable<void> {
//         var url = this.baseUrl + "/api/bills/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "delete",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processBills(response);
//         });
//     }
//
//     private processBills(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "204") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     bills(pk: string, description: string, date: string, amount: string, owner: string, affected_dudes: string): Observable<void> {
//         var url = this.baseUrl + "/api/bills/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "patch",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processBills(response);
//         });
//     }
//
//     private processBills(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     bills(pk: string): Observable<void> {
//         var url = this.baseUrl + "/api/bills/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processBills(response);
//         });
//     }
//
//     private processBills(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     dudes(name: string, still_here: string): Observable<void> {
//         var url = this.baseUrl + "/api/dudes";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "post",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processDudes(response);
//         });
//     }
//
//     private processDudes(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "201") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     dudes(page: string): Observable<void> {
//         var url = this.baseUrl + "/api/dudes?";
//
//         if (page !== undefined)
//             url += "page=" + encodeURIComponent("" + page) + "&";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processDudes(response);
//         });
//     }
//
//     private processDudes(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     payments(pk: string, bill: string, by: string, at: string, amount: string): Observable<void> {
//         var url = this.baseUrl + "/api/payments/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "put",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processPayments(response);
//         });
//     }
//
//     private processPayments(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     payments(pk: string): Observable<void> {
//         var url = this.baseUrl + "/api/payments/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "delete",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processPayments(response);
//         });
//     }
//
//     private processPayments(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "204") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     payments(pk: string, bill: string, by: string, at: string, amount: string): Observable<void> {
//         var url = this.baseUrl + "/api/payments/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "patch",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processPayments(response);
//         });
//     }
//
//     private processPayments(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     payments(pk: string): Observable<void> {
//         var url = this.baseUrl + "/api/payments/{pk}";
//
//         if (pk === undefined || pk === null)
//             throw new Error("The parameter 'pk' must be defined.");
//         url = url.replace("{pk}", encodeURIComponent("" + pk));
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processPayments(response);
//         });
//     }
//
//     private processPayments(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     payments(bill: string, by: string, at: string, amount: string): Observable<void> {
//         var url = this.baseUrl + "/api/payments";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "post",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processPayments(response);
//         });
//     }
//
//     private processPayments(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "201") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
//
//     payments(page: string): Observable<void> {
//         var url = this.baseUrl + "/api/payments?";
//
//         if (page !== undefined)
//             url += "page=" + encodeURIComponent("" + page) + "&";
//
//         var content = "";
//
//         return this.http.request(url, {
//             body: content,
//             method: "get",
//             headers: new Headers({
//                 "Content-Type": "application/json; charset=UTF-8"
//             })
//         }).map((response) => {
//             return this.processPayments(response);
//         });
//     }
//
//     private processPayments(response: Response) {
//         var data = response.text();
//         var status = response.status.toString();
//
//         if (status === "200") {
//         }
//         else
//         {
//             throw "error_no_callback_for_the_received_http_status";
//         }
//     }
// }
//
//
//
// }