# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-10 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_squashed_0002_auto_20160924_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
